import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const avenir = localFont({
  src: [
    {

      path: "../public/fonts/AvenirLTStd-Black.otf",

      weight: "700",
    },
    {
      path: "../public/fonts/AvenirLTStd-Roman.otf",

      weight: "500",
    },
    {
      path: "../public/fonts/AvenirLTStd-Book.otf",
      weight: "400",
    },

  ],
  variable: "--font-avenir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${avenir.variable} antialiased font-avenir`}
      >
        {children}
      </body>
    </html>
  );
}
